# Generated by Django 5.1.4 on 2024-12-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Director', models.CharField(max_length=50)),
                ('ReleaseDate', models.DateField()),
                ('Length', models.IntegerField()),
                ('Description', models.TextField()),
                ('Poster', models.ImageField(upload_to='movies/')),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Start', models.DateField()),
                ('Room', models.IntegerField()),
                ('MovieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Row', models.IntegerField()),
                ('Seat', models.IntegerField()),
                ('CustomerFirsName', models.CharField(max_length=50)),
                ('CustomerLastName', models.CharField(max_length=50)),
                ('CustomerEmail', models.CharField(max_length=50)),
                ('CustomerPhone', models.CharField(max_length=50)),
                ('ScreeningID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.screening')),
            ],
        ),
    ]
