# Generated by Django 5.1.4 on 2024-12-27 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='Start',
            new_name='Start_Date',
        ),
        migrations.AddField(
            model_name='screening',
            name='Start_Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
