version: '3.9'

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./adatbazis_dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet

  web:
    build:
      context: .
      args:
        GIT_REPO: ${GIT_REPO}
        PROJECT_NAME: ${PROJECT_NAME}
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - webnet

volumes:
  postgres_data:

networks:
  webnet:
